{% set name = "cwcwidth" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cwcwidth-{{ version }}.tar.gz
  sha256: c0d647e12e3a4b15a881e1d84f796937516648489e011257237dc2179d6b1951

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython >=0.28
  run:
    - python

test:
  imports:
    - cwcwidth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sebastinas/cwcwidth
  summary: Python bindings for wc(s)width
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
